### ISSUE TITLE
recorder_prefilter.py: recorder_entity_filter(entity_id): TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/recorder_history_prefilter#3]
Just adding this here for tracking:
https://github.com/gcobb321/icloud3/issues/349
https://github.com/enkama/hass-variables/issues/120

```
2024-07-03 13:47:04.948 ERROR (MainThread) [homeassistant.core] Error running job: <Job listen * HassJobType.Callback <function Recorder.async_initialize.._event_listener at 0x7fc27ff76480>>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 1559, in async_fire_internal
self._hass.async_run_hass_job(job, event)
File "/usr/src/homeassistant/homeassistant/core.py", line 938, in async_run_hass_job
hassjob.target(*args)
File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 330, in _event_listener
if entity_filter(entity_id):
^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/icloud3/support/recorder_prefilter.py", line 123, in entity_filter
return recorder_entity_filter(entity_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

Likely from changes made as part of this:
https://developers.home-assistant.io/blog/2024/06/22/excluding-state-attributes-from-recording-match-all/
https://developers.home-assistant.io/docs/core/entity/#excluding-state-attributes-from-recorder-history

**Comment by Snuffy2** [comment]
https://github.com/home-assistant/core/issues/121218

**Comment by Snuffy2** [comment]
Architecture Discussion: https://github.com/home-assistant/architecture/discussions/1106

**Comment by Snuffy2** [comment]
FYI, for `places` and `hass-variables`, I've implemented a kinda klunky workaround by having a child class that inherits from my main entity class that sets `_unrecorded_attributes = frozenset({MATCH_ALL})` as a class attribute. Then in `async_setup_entry` calling `async_add_entities` for the normal vs the no-recorder class.

So I'm not using recorder_history_prefilter at all at least for now. From the [architecture discussion](https://github.com/home-assistant/architecture/discussions/1106), it sounds like they're at least considering the ability to disable a recorder by entity. Fingers crossed.

https://github.com/custom-components/places/pull/290
https://github.com/enkama/hass-variables/pull/121

**Comment by gcobb321** [comment]
I sent bbdraco a msg about the reasons being the prefilter and received a note about joining a discussion on discord. See [here](https://community.home-assistant.io/t/recorder-prefilter/746195). Also another link [here](https://github.com/home-assistant/architecture/discussions/1106)

**Comment by gcobb321** [comment]
I am home from Switzerland and have fixed the iCloud3 recorder-history issue. I had several hardware issues to fix before I could get into it. I turned on my computer and saw smoke coming from inside it's case. It turned out that the video card was fried, probably from some electrical storms and power outages we had while I was away. My Rpi was also fried and failed to boot. Fortunately, I had an older one with 2Gb of memory that was sitting in a closet. I am now using that while I wait for Amazon to bring me a new 8Gb model.

In any case, you will find iCloud3 v3.0.5.5 below. Can you unzip it into the icloud3 directory and restart. Everything should now work as expected. I'll issue a new release if everything is OK.

I found that the `_unrecorded_attributes = frozenset({MATCH_ALL})` was not working. All of the sensor attributes were still being added to the HA recorder history database. I have the sensor Classes structured in a way to have a class for distance, time, text, info, battery, etc. sensors that generate the attributes associated with a parent class for the general updating for the Sensor Entity.

```
Class DeviceSensor_Base(SensorEntity):
   def __init__(---):
   --- lots of code ---
       
Class Sensor_Timer(DeviceSensor_Base):
   _unrecorded_attributes = frozenset({MATCH_ALL})

    def attribute_code():
      --- code for attributes
```
That was not working. Nothing was being excluded. I changed the structure to:
```
Class DeviceSensor_Base():
   def __init__(---):
   --- lots of code ---
       
Class Sensor_Timer(DeviceSensor_Base, SensorEntity):
   _unrecorded_attributes = frozenset({MATCH_ALL})
   
   def attribute_code():
      --- code for attributes
```
That also did not work. What got everything running was specifying the attributes to be excluded for each type of sensor instead of using the MATCH_ALL.
```
_unrecorded_attributes = frozenset(['integration', 'sensor_updated', 'icon', 'friendly_name', 'last_located',...])
```
This may have been caused by various timer type sensors with different attributes that all use the 'Sensor_Timer' class and the class attribute was turning into an instance attribute. I don't know but wanted to give you a heads up on what I ran into.

The places-attrs-ha-history.txt file is the entry in the home-assistant_v2.db history database showing the places attributes when the extended attributes is enabled and disabled. It seemed like a lot of attributes and I'm not sure if the ones that should be excluded are really being excluded. I'm using _SQLite Expert Personal_ to display the ha database (sensor_attributes table).

[icloud3 v3.0.5.5.zip](https://github.com/user-attachments/files/16240108/icloud3.v3.0.5.5.zip)
[places-attrs-in-ha-recorder.txt](https://github.com/user-attachments/files/16240110/places-attrs-in-ha-recorder.txt)

**Comment by Snuffy2** [comment]
Wow! I hope your trip was amazing though. Seems like your tech missed you and revolted (both software and hardware) in response.

It's really weird that specifying SensorEntity in your base class doesn't work but doing it in the inherited child class does. Not sure why that would be. Might be worth a question to HA, but not if you think it will derail the architecture discussion for a better fix in process.

I loaded v3.0.5.5 and everything seems to be ok. However, a number of caveats from my end:
* I've not really gotten any of the recorder errors in ic3, places, or variables. I had done a fully HA reinstall a few months ago so I was likely on the newer DB model which seems to be one of the factors causing the recorder issues
* I've had `sensor.icloud3_event_log` manually excluded in my configuration.yaml. Not sure how long ago I put that in, but it was likely when we were having the recorder issues months (years?) ago, but before you developed the recorder_history_prefilter. I commented out the exclusion yesterday when I upgraded to v3.0.5.5
* Not clear how much of this is ic3 vs apple, but I've been having a number of issues. I was going to discuss this with you/post an issue once you got back and sorted out the recorder stuff. 
    * Every 2-3 days my apple account is getting locked and I'm having to login to icloud.com to manually unlock it
    * Even when my apple account is unlocked, when I restart HA, it seems 50/50 whether ic3 will load all of my trackers or not. My personal tracker (the main one) almost always loads, but the other 4 (connected by Family Sharing) sometimes work and sometime show with a yellow triangle with the logs saying the device wasn't found in Family Sharing. Restarting ic3 doesn't seem to fix it and I need to restart HA to get it to work again. Sometimes I've had to restart HA >1 to get these 4 trackers to work again. I'm sure this is not enough to go on and I will get you logs in an issue. However this issue is still happening with v3.0.5.5 but doesn't seem any different than what it was on earlier versions and before HA 2024.7.

Regarding MATCH_ALL in places:
* The txt file and what you are seeing in the db is interesting. I'm not quite sure what to make of it. As you noted, it does appear that it isn't working.
* I was basing my determination of whether it was working or not based on if I got the alert in the HA logs that my sensor exceeded the 16k size and that the attributes wouldn't be saved to the recorder.
* Taking out all things from places related to the recorder, when I enabled extended_attr, I'll get the recorder size alert.
    * Prior to 2024.7 using recorder_history_prefilter, it prevented the recorder size alert
    * When running the current, hacky workaround I'm running with places v2.7.1, I also don't get the recorder size alert
* Not sure how to reconcile that you are seeing the attributes in the db event with extended_attr enabled but I presume you're not seeing the recorder size alert in your logs?
* For now, until they sort out how they may want to fix this in HA from the architecture discussion, I'm inclined to leave my current workaround in places and variables (they use the same workaround).
